#!/usr/bin/make -f
#-*- mode:makefile -*-

newClient:
	curl -X POST -H "Content-Type: application/Json" -d '{"email":"email@gmail.com", "pass":"ajdfksd", "address":"calle", "phone":"66666666"}' https://natural-bus-135323.appspot.com/clients
	curl -X POST -H "Content-Type: application/Json" -d '{"email":"email2@gmail.com", "pass":"ajdfksd", "address":"calle", "phone":"66666666"}'  https://natural-bus-135323.appspot.com/clients


addCart:
	curl -X POST -H "Content-Type: application/Json" -d '{"name":"Blanco"}' https://natural-bus-135323.appspot.com/clients/ahRzfm5hdHVyYWwtYnVzLTEzNTMyM3IUCxIHQ2xpZW50cxiAgICA3qWFCgw/carts 
	curl -X POST -H "Content-Type: application/Json" -d '{"name":"Navidad"}' https://natural-bus-135323.appspot.com/clients/ahRzfm5hdHVyYWwtYnVzLTEzNTMyM3IUCxIHQ2xpZW50cxiAgICA3qWFCgw/carts
	curl -X POST -H "Content-Type: application/Json" -d '{"name":"Nochevieja"}'  https://natural-bus-135323.appspot.com/clients/ahRzfm5hdHVyYWwtYnVzLTEzNTMyM3IUCxIHQ2xpZW50cxiAgICA3qWFCgw/carts

addWine:	
	curl -X POST -H "Content-Type: application/Json" -d '{"name":"Rosa", "type":"Rosado", "grade":12.4 , "size":75, "varietals":"nsnc", "do":false, "price":54, "photo":"Gepeto" }' https://natural-bus-135323.appspot.com/wines 
	curl -X POST -H "Content-Type: application/Json" -d '{"name":"Senorio de los Llanos", "type":"Tinto", "grade":12.4 , "size":75, "varietals":"nsnc", "do":false, "price":12, "photo":"Gepeto" }'  https://natural-bus-135323.appspot.com/wines
	curl -X POST -H "Content-Type: application/Json" -d '{"name":"Black", "type":"Tinto", "grade":12.4 , "size":75, "varietals":"nsnc", "do":false, "price":15, "photo":"Gepeto", "cask":"hola", "bottle":"botella"}'  https://natural-bus-135323.appspot.com/wines


addItem:
	curl -X POST -H "Content-Type: application/Json" -d '{"name":"Yugo"}'  https://natural-bus-135323.appspot.com/clients/ahRzfm5hdHVyYWwtYnVzLTEzNTMyM3IUCxIHQ2xpZW50cxiAgICAmZnNCAw/carts/ahRzfm5hdHVyYWwtYnVzLTEzNTMyM3ImCxIHQ2xpZW50cxiAgICA3qWFCgwLEgVDYXJ0cxiAgICAgICACgw/items
	curl -X POST -H "Content-Type: application/Json" -d '{"name":"DonSimon"}'  https://natural-bus-135323.appspot.com/clients/ahRzfm5hdHVyYWwtYnVzLTEzNTMyM3IUCxIHQ2xpZW50cxiAgICAmZnNCAw/carts/ahRzfm5hdHVyYWwtYnVzLTEzNTMyM3ImCxIHQ2xpZW50cxiAgICA3qWFCgwLEgVDYXJ0cxiAgICAgICACgw/items









